# Generated by Django 3.0.5 on 2020-04-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearnTemplateModel',
            new_name='LearnTemplate',
        ),
    ]
