# Generated by Django 3.0.5 on 2020-04-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20200411_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='learntemplate',
            name='description',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
