# Generated by Django 3.0.5 on 2020-04-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_learntemplate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='learntemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%d-%m-%y/'),
        ),
    ]
